name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'  # 只在以 v 开头的标签推送时触发，例如 v1.0.0
  workflow_dispatch:  # 添加人工触发    

jobs:
  release:
    name: Release Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
      issues: write
    steps:
      # - name: 清理临时文件
      #   run: |
      #     sudo rm -rf /tmp/*
      #     sudo rm -rf ~/.npm
      #     sudo rm -rf ~/.cache
      #     sudo rm -rf /home/runner/runners/2.323.0/_diag/*.log
      #     sudo apt-get clean  

      # - name: Free Disk Space
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: true

      #     # all of these default to true, but feel free to set to
      #     # false if necessary for your workflow
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: false
      #     docker-images: false
      #     swap-storage: false    

      - name: Check out the repo
        uses: actions/checkout@v4



      - name: Clean up Docker to free space
        run: |
          docker system prune -a --volumes -f  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}       

      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3    

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            nathubs/rknn-developer:${{ env.VERSION }}
            nathubs/rknn-developer:latest
          platforms: linux/amd64